### ISSUE TITLE
Memory Leaks!

### ISSUE THREAD

**Issue by ywwyewenwei** [yamoe/ven#1]
Hi,
     I am using your code in my project.
     My client is a dialog based application.  the code like below:
BOOL CMyGuiDlg::OnInitDialog()
{
      // do some initializing...
      InitNet();
}

void CMyGuiDlg::InitNet()
{
	m_pNet = new ven::Net;
	if ( m_pNet )
	{
		m_pSession = m_pNet->run_tcp_client<Session>({ "XXX.XXX.XXX.XXX", XXX });
		if ( m_pSession )
		{
			m_pSession->connect();
		}
	}
}

And befor the dialog exits,  I call UnInitNet() :
void CMyGuiDlg::UnInitNet()
{
	if ( m_pSession )
	{
		m_pSession->disconnect();
	}
	m_pNet->stop_tcp_client( m_pSession );
	delete m_pNet;
	m_pNet = NULL;
}

When tha application exits, VS2017 IDE will report so many memory leaks:
f:\study\huobi\huobi\huobiserver\3partlib\ven\ven\include\ven\mem\mem_pool.h(130) : {11980} normal block at 0x00000206DF1D1DF0, 2048 bytes long.
 Data: <                > CD CD CD CD CD CD CD CD CD CD CD CD CD CD CD CD 
{11979} normal block at 0x00000206DF1D0D60, 40 bytes long.
 Data: <                > 80 13 1D DF 06 02 00 00 F0 1D 1D DF 06 02 00 00 
f:\study\huobi\huobi\huobiserver\3partlib\ven\ven\include\ven\mem\mem_pool.h(130) : {11978} normal block at 0x00000206DF1D15B0, 2048 bytes long.
 Data: <                > CD CD CD CD CD CD CD CD CD CD CD CD CD CD CD CD 
{11977} normal block at 0x00000206DF1D1380, 40 bytes long.
 Data: <                > D0 8C 1C DF 06 02 00 00 B0 15 1D DF 06 02 00 00 
f:\study\huobi\huobi\huobiserver\3partlib\ven\ven\include\ven\mem\mem_pool.h(130) : {11976} normal block at 0x00000206DF1CFD60, 2048 bytes long.
 Data: <                > CD CD CD CD CD CD CD CD CD CD CD CD CD CD CD CD 
{11975} normal block at 0x00000206DF1C8CD0, 40 bytes long.
 Data: <`       `       > 60 8C 1C DF 06 02 00 00 60 FD 1C DF 06 02 00 00 
f:\study\huobi\huobi\huobiserver\3partlib\ven\ven\include\ven\mem\mem_pool.h(130) : {11974} normal block at 0x00000206DF1CF520, 2048 bytes long.
 Data: <                > CD CD CD CD CD CD CD CD CD CD CD CD CD CD CD CD 
{11973} normal block at 0x00000206DF1C8C60, 40 bytes long.
 Data: <                > A0 8A 1C DF 06 02 00 00 20 F5 1C DF 06 02 00 00 
f:\study\huobi\huobi\huobiserver\3partlib\ven\ven\include\ven\mem\mem_pool.h(130) : {11972} normal block at 0x00000206DF1CECE0, 2048 bytes long.
 Data: <                > CD CD CD CD CD CD CD CD CD CD CD CD CD CD CD CD 
{11971} normal block at 0x00000206DF1C8AA0, 40 bytes long.
 Data: <                > F0 8B 1C DF 06 02 00 00 E0 EC 1C DF 06 02 00 00 

 Can you tell me how to fix it ?
 Best regards.

**Comment by yamoe** [comment]
I intended to automatically clean up the memory by windows. (at the end of the process)
anyway, i tried to fix it and commited to master branch.

this project is fragile. just use test purpose.
Thank you.

**Comment by ywwyewenwei** [comment]
OK. Thanks a lot
